//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFText
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public System.Guid Id { get; set; }
        public string OrderNum { get; set; }
        public string CreateTime { get; set; }
        public int TecherId { get; set; }
    
        public virtual Techer Techer { get; set; }
    }
}
